name: RunAnk

on: pull_request

jobs:
  type_checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          architecture: x64
      - name: Clean build
        env:
          JAVA_OPTS: -Xms512m -Xmx1024m
        run: |
          java -version
          ./gradlew -v
          ./gradlew clean build
      - name: Run Ank
        env:
          JAVA_OPTS: -Xms512m -Xmx1024m
        run: ./gradlew runAnk